        // Existing code...

        // Button event handlers
        this.btnSourceBrowse.Click += new System.EventHandler(this.btnSourceBrowse_Click);
        // Existing code...

        // Existing code...

        // Button event handlers
        this.btnDestinationBrowse.Click += new System.EventHandler(this.btnDestinationBrowse_Click);
        // Existing code...

        // Existing code...

        // Button event handlers
        this.btnChange.Click += new System.EventHandler(this.btnChange_Click);
        // Existing code...

        // Existing code...

        // Button event handlers
        this.btnEsc.Click += new System.EventHandler(this.btnEsc_Click);
        // Existing code...